export type AppConfig = {
  nodeEnv: string;
  name: string;
  workingDirectory: string;
  frontendDomain?: string;
  backendDomain: string;
  port: number;
  apiPrefix: string;
  fallbackLanguage: string;
  headerLanguage: string;
  databaseUrl?: string;
  persistenceDriver: 'memory' | 'prisma';
  wechatAppId?: string;
  wechatAppSecret?: string;
  authTokenSecret?: string;
  authTokenTtlSeconds?: number;
  wechatReminderTemplateId?: string;
  wechatSubscriptionType?: 'once' | 'long_term';
  wechatMessageState?: 'formal' | 'developer' | 'trial';
  notificationSchedulerEnabled?: boolean;
};
